services:
  dash:
    image: haggy24/truck-emission-monitoring:latest
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_ORG: acme
      INFLUX_BUCKET: telemetry
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      DASH_TITLE: "Truck Air Quality"
      APP_REFRESH_MS: "5000"
      TZ: "Asia/Jakarta"
    ports:
      - "18050:8050"
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.178

networks:
  nginx-manager_customnetwork:
    external: true

